# 使用官方 Node.js 映像作為基礎映像
FROM node:alpine

# 設置工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json 並安裝依賴項
COPY package.json .

RUN npm install

COPY . .

# Build 
RUN npm run build

# 運行應用程式
CMD [ "npm", "run", "start" ]