# 使用官方 Node.js 映像作為基礎映像
FROM node:alpine

# 設置工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json 並安裝依賴項
COPY package*.json ./

#-only=prod: prod是指production 意思為只安裝package.json的dependencies裡的套件，忽略devDependencies裡的套件
RUN npm install -only=prod

# 複製編譯後的 JavaScript 程式碼(位於dist/目錄中)到容器中的/app目錄
COPY dist/ .

# 運行應用程式
CMD ["node", "index.js"]