apiVersion: apps/v1
kind: Deployment
metadata:
  name: geetogether-pictures-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geetogether-pictures
  template:
    metadata:
      labels:
        app: geetogether-pictures
    spec:
      containers:
        - name: geetogether-pictures
          image: 594leonhuang/geetogether-pictures
          env:
            - name: RABBIT_HOST
              value: 'hello-world'
            - name: RABBIT_PORT
              value: '5672'
            - name: RABBIT_QUEUE
              value: 'pictures'
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hello-world-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-world-default-user
                  key: password
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBIT_SECRET
              value: "hello-world-default-user"
            - name: K8S_NAMESPACE
              value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: geetogether-pictures-srv
spec:
  selector:
    app: geetogether-pictures
  type: ClusterIP
  ports:
    - name: geetogether-pictures-port
      protocol: TCP
      port: 3000
      targetPort: 3000
