apiVersion: apps/v1
kind: Deployment
metadata:
  name: geetogether-profiles-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geetogether-profiles
  template:
    metadata:
      labels:
        app: geetogether-profiles
    spec:
      containers:
        - name: geetogether-profiles
          image: 594leonhuang/geetogether-profiles
          env:
            - name: MONGO_URI
              value: 'mongodb://geetogether-profiles-mongo-srv:27017'
            - name: MONGO_DB_NAME
              value: 'profiles'
            - name: RABBIT_HOST
              value: 'hello-world'
            - name: RABBIT_PORT
              value: '5672'
            - name: RABBIT_QUEUE
              value: 'profiles' 
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hello-world-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-world-default-user
                  key: password
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBIT_SECRET
              value: "hello-world-default-user"
            - name: K8S_NAMESPACE
              value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: geetogether-profiles-srv
spec:
  selector:
    app: geetogether-profiles
  type: ClusterIP
  ports:
    - name: geetogether-profiles-port
      protocol: TCP
      port: 3000
      targetPort: 3000
