name: Deploy Manifests to GKE

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: 'geetogether-gcproj'

    - name: Configure kubectl context
      run: gcloud container clusters get-credentials geetogether-cluster --zone asia-east1 --project geetogether-gcproj

    - name: Deploy to GKE
      run: |
        kubectl apply -f infra/k8s
        kubectl apply -f infra/k8s-prod
