name: tests-timelines

on:
  pull_request:
    paths:
      - 'timelines/**'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd timelines && npm install && npm run test:ci
